name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  # flutter_local_notifications: 16.1.0   <-- REMOVE THIS LINE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/splashlogo.png
    - assets/images/applogo.png

flutter_launcher_icons:
  image_path: assets/images/applogo.png
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/images/applogo.png
    background_color: "#161B33"
    theme_color: "#161B33"
  macos:
    generate: true
    image_path: assets/images/applogo.png
  windows:
    generate: true
    image_path: assets/images/applogo.png
